[package]
name = "cfs-md"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
bytes.workspace = true
flatbuffers = { workspace = true, features = ["serialize"]}
tokio.workspace = true
tracing.workspace = true
