[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
cfs-core.workspace = true
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
glob.workspace = true
walkdir.workspace = true
xshell.workspace = true
