// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_FILE_TYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_FILE_TYPE: i8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_FILE_TYPE: [FileType; 3] = [
  FileType::Regular,
  FileType::Directory,
  FileType::Symlink,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct FileType(pub i8);
#[allow(non_upper_case_globals)]
impl FileType {
  pub const Regular: Self = Self(0);
  pub const Directory: Self = Self(1);
  pub const Symlink: Self = Self(2);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Regular,
    Self::Directory,
    Self::Symlink,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Regular => Some("Regular"),
      Self::Directory => Some("Directory"),
      Self::Symlink => Some("Symlink"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for FileType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for FileType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for FileType {
    type Output = FileType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for FileType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for FileType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for FileType {}
// struct Timespec, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Timespec(pub [u8; 16]);
impl Default for Timespec { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl core::fmt::Debug for Timespec {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Timespec")
      .field("sec", &self.sec())
      .field("nsec", &self.nsec())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Timespec {}
impl<'a> flatbuffers::Follow<'a> for Timespec {
  type Inner = &'a Timespec;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Timespec>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Timespec {
  type Inner = &'a Timespec;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Timespec>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Timespec {
    type Output = Timespec;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const Timespec as *const u8, <Self as flatbuffers::Push>::size());
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> flatbuffers::Verifiable for Timespec {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Timespec {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    sec: u64,
    nsec: u32,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_sec(sec);
    s.set_nsec(nsec);
    s
  }

  pub fn sec(&self) -> u64 {
    let mut mem = core::mem::MaybeUninit::<<u64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_sec(&mut self, x: u64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn nsec(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<<u32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_nsec(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum DirEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DirEntry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DirEntry<'a> {
  type Inner = DirEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> DirEntry<'a> {
  pub const VT_INO: flatbuffers::VOffsetT = 4;
  pub const VT_PARENT_INO: flatbuffers::VOffsetT = 6;
  pub const VT_SIZE: flatbuffers::VOffsetT = 8;
  pub const VT_MTIME: flatbuffers::VOffsetT = 10;
  pub const VT_CTIME: flatbuffers::VOffsetT = 12;
  pub const VT_KIND: flatbuffers::VOffsetT = 14;
  pub const VT_PERM: flatbuffers::VOffsetT = 16;
  pub const VT_UID: flatbuffers::VOffsetT = 18;
  pub const VT_GID: flatbuffers::VOffsetT = 20;
  pub const VT_NAME: flatbuffers::VOffsetT = 22;
  pub const VT_S3_OFFSET: flatbuffers::VOffsetT = 24;
  pub const VT_S3_SIZE: flatbuffers::VOffsetT = 26;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DirEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DirEntryArgs<'args>
  ) -> flatbuffers::WIPOffset<DirEntry<'bldr>> {
    let mut builder = DirEntryBuilder::new(_fbb);
    builder.add_s3_size(args.s3_size);
    builder.add_s3_offset(args.s3_offset);
    builder.add_size(args.size);
    builder.add_parent_ino(args.parent_ino);
    builder.add_ino(args.ino);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_gid(args.gid);
    builder.add_uid(args.uid);
    if let Some(x) = args.ctime { builder.add_ctime(x); }
    if let Some(x) = args.mtime { builder.add_mtime(x); }
    builder.add_perm(args.perm);
    builder.add_kind(args.kind);
    builder.finish()
  }


  #[inline]
  pub fn ino(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DirEntry::VT_INO, Some(0)).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &DirEntry) -> bool {
    self.ino() < o.ino()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: u64) -> ::core::cmp::Ordering {
    let key = self.ino();
    key.cmp(&val)
  }
  #[inline]
  pub fn parent_ino(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DirEntry::VT_PARENT_INO, Some(0)).unwrap()}
  }
  #[inline]
  pub fn size(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DirEntry::VT_SIZE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn mtime(&self) -> &'a Timespec {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Timespec>(DirEntry::VT_MTIME, None).unwrap()}
  }
  #[inline]
  pub fn ctime(&self) -> &'a Timespec {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Timespec>(DirEntry::VT_CTIME, None).unwrap()}
  }
  #[inline]
  pub fn kind(&self) -> FileType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<FileType>(DirEntry::VT_KIND, Some(FileType::Regular)).unwrap()}
  }
  #[inline]
  pub fn perm(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(DirEntry::VT_PERM, Some(0)).unwrap()}
  }
  #[inline]
  pub fn uid(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(DirEntry::VT_UID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn gid(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(DirEntry::VT_GID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DirEntry::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn s3_offset(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DirEntry::VT_S3_OFFSET, Some(0)).unwrap()}
  }
  #[inline]
  pub fn s3_size(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DirEntry::VT_S3_SIZE, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for DirEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("ino", Self::VT_INO, false)?
     .visit_field::<u64>("parent_ino", Self::VT_PARENT_INO, false)?
     .visit_field::<u64>("size", Self::VT_SIZE, false)?
     .visit_field::<Timespec>("mtime", Self::VT_MTIME, true)?
     .visit_field::<Timespec>("ctime", Self::VT_CTIME, true)?
     .visit_field::<FileType>("kind", Self::VT_KIND, false)?
     .visit_field::<u16>("perm", Self::VT_PERM, false)?
     .visit_field::<u32>("uid", Self::VT_UID, false)?
     .visit_field::<u32>("gid", Self::VT_GID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<u64>("s3_offset", Self::VT_S3_OFFSET, false)?
     .visit_field::<u64>("s3_size", Self::VT_S3_SIZE, false)?
     .finish();
    Ok(())
  }
}
pub struct DirEntryArgs<'a> {
    pub ino: u64,
    pub parent_ino: u64,
    pub size: u64,
    pub mtime: Option<&'a Timespec>,
    pub ctime: Option<&'a Timespec>,
    pub kind: FileType,
    pub perm: u16,
    pub uid: u32,
    pub gid: u32,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub s3_offset: u64,
    pub s3_size: u64,
}
impl<'a> Default for DirEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    DirEntryArgs {
      ino: 0,
      parent_ino: 0,
      size: 0,
      mtime: None, // required field
      ctime: None, // required field
      kind: FileType::Regular,
      perm: 0,
      uid: 0,
      gid: 0,
      name: None, // required field
      s3_offset: 0,
      s3_size: 0,
    }
  }
}

pub struct DirEntryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DirEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ino(&mut self, ino: u64) {
    self.fbb_.push_slot::<u64>(DirEntry::VT_INO, ino, 0);
  }
  #[inline]
  pub fn add_parent_ino(&mut self, parent_ino: u64) {
    self.fbb_.push_slot::<u64>(DirEntry::VT_PARENT_INO, parent_ino, 0);
  }
  #[inline]
  pub fn add_size(&mut self, size: u64) {
    self.fbb_.push_slot::<u64>(DirEntry::VT_SIZE, size, 0);
  }
  #[inline]
  pub fn add_mtime(&mut self, mtime: &Timespec) {
    self.fbb_.push_slot_always::<&Timespec>(DirEntry::VT_MTIME, mtime);
  }
  #[inline]
  pub fn add_ctime(&mut self, ctime: &Timespec) {
    self.fbb_.push_slot_always::<&Timespec>(DirEntry::VT_CTIME, ctime);
  }
  #[inline]
  pub fn add_kind(&mut self, kind: FileType) {
    self.fbb_.push_slot::<FileType>(DirEntry::VT_KIND, kind, FileType::Regular);
  }
  #[inline]
  pub fn add_perm(&mut self, perm: u16) {
    self.fbb_.push_slot::<u16>(DirEntry::VT_PERM, perm, 0);
  }
  #[inline]
  pub fn add_uid(&mut self, uid: u32) {
    self.fbb_.push_slot::<u32>(DirEntry::VT_UID, uid, 0);
  }
  #[inline]
  pub fn add_gid(&mut self, gid: u32) {
    self.fbb_.push_slot::<u32>(DirEntry::VT_GID, gid, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DirEntry::VT_NAME, name);
  }
  #[inline]
  pub fn add_s3_offset(&mut self, s3_offset: u64) {
    self.fbb_.push_slot::<u64>(DirEntry::VT_S3_OFFSET, s3_offset, 0);
  }
  #[inline]
  pub fn add_s3_size(&mut self, s3_size: u64) {
    self.fbb_.push_slot::<u64>(DirEntry::VT_S3_SIZE, s3_size, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> DirEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DirEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DirEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, DirEntry::VT_MTIME,"mtime");
    self.fbb_.required(o, DirEntry::VT_CTIME,"ctime");
    self.fbb_.required(o, DirEntry::VT_NAME,"name");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DirEntry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DirEntry");
      ds.field("ino", &self.ino());
      ds.field("parent_ino", &self.parent_ino());
      ds.field("size", &self.size());
      ds.field("mtime", &self.mtime());
      ds.field("ctime", &self.ctime());
      ds.field("kind", &self.kind());
      ds.field("perm", &self.perm());
      ds.field("uid", &self.uid());
      ds.field("gid", &self.gid());
      ds.field("name", &self.name());
      ds.field("s3_offset", &self.s3_offset());
      ds.field("s3_size", &self.s3_size());
      ds.finish()
  }
}
pub enum DirEntryPageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DirEntryPage<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DirEntryPage<'a> {
  type Inner = DirEntryPage<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> DirEntryPage<'a> {
  pub const VT_DIRENTS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DirEntryPage { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DirEntryPageArgs<'args>
  ) -> flatbuffers::WIPOffset<DirEntryPage<'bldr>> {
    let mut builder = DirEntryPageBuilder::new(_fbb);
    if let Some(x) = args.dirents { builder.add_dirents(x); }
    builder.finish()
  }


  #[inline]
  pub fn dirents(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DirEntry<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DirEntry>>>>(DirEntryPage::VT_DIRENTS, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for DirEntryPage<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<DirEntry>>>>("dirents", Self::VT_DIRENTS, true)?
     .finish();
    Ok(())
  }
}
pub struct DirEntryPageArgs<'a> {
    pub dirents: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DirEntry<'a>>>>>,
}
impl<'a> Default for DirEntryPageArgs<'a> {
  #[inline]
  fn default() -> Self {
    DirEntryPageArgs {
      dirents: None, // required field
    }
  }
}

pub struct DirEntryPageBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DirEntryPageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_dirents(&mut self, dirents: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<DirEntry<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DirEntryPage::VT_DIRENTS, dirents);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> DirEntryPageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DirEntryPageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DirEntryPage<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, DirEntryPage::VT_DIRENTS,"dirents");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DirEntryPage<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DirEntryPage");
      ds.field("dirents", &self.dirents());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `DirEntryPage`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_dir_entry_page_unchecked`.
pub fn root_as_dir_entry_page(buf: &[u8]) -> Result<DirEntryPage, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<DirEntryPage>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `DirEntryPage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_dir_entry_page_unchecked`.
pub fn size_prefixed_root_as_dir_entry_page(buf: &[u8]) -> Result<DirEntryPage, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<DirEntryPage>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `DirEntryPage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_dir_entry_page_unchecked`.
pub fn root_as_dir_entry_page_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<DirEntryPage<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<DirEntryPage<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `DirEntryPage` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_dir_entry_page_unchecked`.
pub fn size_prefixed_root_as_dir_entry_page_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<DirEntryPage<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<DirEntryPage<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a DirEntryPage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `DirEntryPage`.
pub unsafe fn root_as_dir_entry_page_unchecked(buf: &[u8]) -> DirEntryPage {
  flatbuffers::root_unchecked::<DirEntryPage>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed DirEntryPage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `DirEntryPage`.
pub unsafe fn size_prefixed_root_as_dir_entry_page_unchecked(buf: &[u8]) -> DirEntryPage {
  flatbuffers::size_prefixed_root_unchecked::<DirEntryPage>(buf)
}
#[inline]
pub fn finish_dir_entry_page_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<DirEntryPage<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_dir_entry_page_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<DirEntryPage<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
