// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_FILE_TYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_FILE_TYPE: i8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_FILE_TYPE: [FileType; 3] = [
  FileType::Regular,
  FileType::Directory,
  FileType::Symlink,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct FileType(pub i8);
#[allow(non_upper_case_globals)]
impl FileType {
  pub const Regular: Self = Self(0);
  pub const Directory: Self = Self(1);
  pub const Symlink: Self = Self(2);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Regular,
    Self::Directory,
    Self::Symlink,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Regular => Some("Regular"),
      Self::Directory => Some("Directory"),
      Self::Symlink => Some("Symlink"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for FileType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for FileType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for FileType {
    type Output = FileType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<i8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for FileType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for FileType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for FileType {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_LOCATION: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_LOCATION: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_LOCATION: [Location; 3] = [
  Location::NONE,
  Location::local,
  Location::s3,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Location(pub u8);
#[allow(non_upper_case_globals)]
impl Location {
  pub const NONE: Self = Self(0);
  pub const local: Self = Self(1);
  pub const s3: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::local,
    Self::s3,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::local => Some("local"),
      Self::s3 => Some("s3"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for Location {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for Location {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for Location {
    type Output = Location;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<u8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for Location {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for Location {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Location {}
pub struct LocationUnionTableOffset {}

// struct Timespec, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Timespec(pub [u8; 16]);
impl Default for Timespec { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl core::fmt::Debug for Timespec {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Timespec")
      .field("sec", &self.sec())
      .field("nsec", &self.nsec())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Timespec {}
impl<'a> flatbuffers::Follow<'a> for Timespec {
  type Inner = &'a Timespec;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a Timespec>::follow(buf, loc) }
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Timespec {
  type Inner = &'a Timespec;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { flatbuffers::follow_cast_ref::<Timespec>(buf, loc) }
  }
}
impl<'b> flatbuffers::Push for Timespec {
    type Output = Timespec;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const Timespec as *const u8, <Self as flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> flatbuffers::Verifiable for Timespec {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Timespec {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    sec: u64,
    nsec: u32,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_sec(sec);
    s.set_nsec(nsec);
    s
  }

  pub fn sec(&self) -> u64 {
    let mut mem = core::mem::MaybeUninit::<<u64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_sec(&mut self, x: u64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn nsec(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<<u32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_nsec(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct ByteRange, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct ByteRange(pub [u8; 16]);
impl Default for ByteRange { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl core::fmt::Debug for ByteRange {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("ByteRange")
      .field("offset", &self.offset())
      .field("length", &self.length())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ByteRange {}
impl<'a> flatbuffers::Follow<'a> for ByteRange {
  type Inner = &'a ByteRange;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a ByteRange>::follow(buf, loc) }
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a ByteRange {
  type Inner = &'a ByteRange;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { flatbuffers::follow_cast_ref::<ByteRange>(buf, loc) }
  }
}
impl<'b> flatbuffers::Push for ByteRange {
    type Output = ByteRange;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const ByteRange as *const u8, <Self as flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> flatbuffers::Verifiable for ByteRange {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> ByteRange {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    offset: u64,
    length: u64,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_offset(offset);
    s.set_length(length);
    s
  }

  pub fn offset(&self) -> u64 {
    let mut mem = core::mem::MaybeUninit::<<u64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_offset(&mut self, x: u64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn length(&self) -> u64 {
    let mut mem = core::mem::MaybeUninit::<<u64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_length(&mut self, x: u64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<<u64 as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum S3LocationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct S3Location<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for S3Location<'a> {
  type Inner = S3Location<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> S3Location<'a> {
  pub const VT_BUCKET: flatbuffers::VOffsetT = 4;
  pub const VT_KEY: flatbuffers::VOffsetT = 6;
  pub const VT_LENGTH: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    S3Location { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args S3LocationArgs<'args>
  ) -> flatbuffers::WIPOffset<S3Location<'bldr>> {
    let mut builder = S3LocationBuilder::new(_fbb);
    builder.add_length(args.length);
    if let Some(x) = args.key { builder.add_key(x); }
    if let Some(x) = args.bucket { builder.add_bucket(x); }
    builder.finish()
  }


  #[inline]
  pub fn bucket(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(S3Location::VT_BUCKET, None).unwrap()}
  }
  #[inline]
  pub fn key(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(S3Location::VT_KEY, None).unwrap()}
  }
  #[inline]
  pub fn length(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(S3Location::VT_LENGTH, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for S3Location<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("bucket", Self::VT_BUCKET, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, true)?
     .visit_field::<u64>("length", Self::VT_LENGTH, false)?
     .finish();
    Ok(())
  }
}
pub struct S3LocationArgs<'a> {
    pub bucket: Option<flatbuffers::WIPOffset<&'a str>>,
    pub key: Option<flatbuffers::WIPOffset<&'a str>>,
    pub length: u64,
}
impl<'a> Default for S3LocationArgs<'a> {
  #[inline]
  fn default() -> Self {
    S3LocationArgs {
      bucket: None, // required field
      key: None, // required field
      length: 0,
    }
  }
}

pub struct S3LocationBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> S3LocationBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_bucket(&mut self, bucket: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(S3Location::VT_BUCKET, bucket);
  }
  #[inline]
  pub fn add_key(&mut self, key: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(S3Location::VT_KEY, key);
  }
  #[inline]
  pub fn add_length(&mut self, length: u64) {
    self.fbb_.push_slot::<u64>(S3Location::VT_LENGTH, length, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> S3LocationBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    S3LocationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<S3Location<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, S3Location::VT_BUCKET,"bucket");
    self.fbb_.required(o, S3Location::VT_KEY,"key");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for S3Location<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("S3Location");
      ds.field("bucket", &self.bucket());
      ds.field("key", &self.key());
      ds.field("length", &self.length());
      ds.finish()
  }
}
pub enum LocalLocationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LocalLocation<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for LocalLocation<'a> {
  type Inner = LocalLocation<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LocalLocation<'a> {
  pub const VT_PATH: flatbuffers::VOffsetT = 4;
  pub const VT_LENGTH: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    LocalLocation { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LocalLocationArgs<'args>
  ) -> flatbuffers::WIPOffset<LocalLocation<'bldr>> {
    let mut builder = LocalLocationBuilder::new(_fbb);
    builder.add_length(args.length);
    if let Some(x) = args.path { builder.add_path(x); }
    builder.finish()
  }


  #[inline]
  pub fn path(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(LocalLocation::VT_PATH, None).unwrap()}
  }
  #[inline]
  pub fn length(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(LocalLocation::VT_LENGTH, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for LocalLocation<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("path", Self::VT_PATH, true)?
     .visit_field::<u64>("length", Self::VT_LENGTH, false)?
     .finish();
    Ok(())
  }
}
pub struct LocalLocationArgs<'a> {
    pub path: Option<flatbuffers::WIPOffset<&'a str>>,
    pub length: u64,
}
impl<'a> Default for LocalLocationArgs<'a> {
  #[inline]
  fn default() -> Self {
    LocalLocationArgs {
      path: None, // required field
      length: 0,
    }
  }
}

pub struct LocalLocationBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LocalLocationBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_path(&mut self, path: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LocalLocation::VT_PATH, path);
  }
  #[inline]
  pub fn add_length(&mut self, length: u64) {
    self.fbb_.push_slot::<u64>(LocalLocation::VT_LENGTH, length, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> LocalLocationBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LocalLocationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<LocalLocation<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, LocalLocation::VT_PATH,"path");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for LocalLocation<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("LocalLocation");
      ds.field("path", &self.path());
      ds.field("length", &self.length());
      ds.finish()
  }
}
pub enum LocationWrapperOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LocationWrapper<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for LocationWrapper<'a> {
  type Inner = LocationWrapper<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LocationWrapper<'a> {
  pub const VT_LOCATION_TYPE: flatbuffers::VOffsetT = 4;
  pub const VT_LOCATION: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    LocationWrapper { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LocationWrapperArgs
  ) -> flatbuffers::WIPOffset<LocationWrapper<'bldr>> {
    let mut builder = LocationWrapperBuilder::new(_fbb);
    if let Some(x) = args.location { builder.add_location(x); }
    builder.add_location_type(args.location_type);
    builder.finish()
  }


  #[inline]
  pub fn location_type(&self) -> Location {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Location>(LocationWrapper::VT_LOCATION_TYPE, Some(Location::NONE)).unwrap()}
  }
  #[inline]
  pub fn location(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(LocationWrapper::VT_LOCATION, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn location_as_local(&self) -> Option<LocalLocation<'a>> {
    if self.location_type() == Location::local {
      self.location().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { LocalLocation::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn location_as_s_3(&self) -> Option<S3Location<'a>> {
    if self.location_type() == Location::s3 {
      self.location().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { S3Location::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for LocationWrapper<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_union::<Location, _>("location_type", Self::VT_LOCATION_TYPE, "location", Self::VT_LOCATION, false, |key, v, pos| {
        match key {
          Location::local => v.verify_union_variant::<flatbuffers::ForwardsUOffset<LocalLocation>>("Location::local", pos),
          Location::s3 => v.verify_union_variant::<flatbuffers::ForwardsUOffset<S3Location>>("Location::s3", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct LocationWrapperArgs {
    pub location_type: Location,
    pub location: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for LocationWrapperArgs {
  #[inline]
  fn default() -> Self {
    LocationWrapperArgs {
      location_type: Location::NONE,
      location: None,
    }
  }
}

pub struct LocationWrapperBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LocationWrapperBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_location_type(&mut self, location_type: Location) {
    self.fbb_.push_slot::<Location>(LocationWrapper::VT_LOCATION_TYPE, location_type, Location::NONE);
  }
  #[inline]
  pub fn add_location(&mut self, location: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LocationWrapper::VT_LOCATION, location);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> LocationWrapperBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LocationWrapperBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<LocationWrapper<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for LocationWrapper<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("LocationWrapper");
      ds.field("location_type", &self.location_type());
      match self.location_type() {
        Location::local => {
          if let Some(x) = self.location_as_local() {
            ds.field("location", &x)
          } else {
            ds.field("location", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Location::s3 => {
          if let Some(x) = self.location_as_s_3() {
            ds.field("location", &x)
          } else {
            ds.field("location", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("location", &x)
        },
      };
      ds.finish()
  }
}
pub enum LocationRefOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LocationRef<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for LocationRef<'a> {
  type Inner = LocationRef<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LocationRef<'a> {
  pub const VT_LOCATION_INDEX: flatbuffers::VOffsetT = 4;
  pub const VT_BYTE_RANGE: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    LocationRef { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LocationRefArgs<'args>
  ) -> flatbuffers::WIPOffset<LocationRef<'bldr>> {
    let mut builder = LocationRefBuilder::new(_fbb);
    if let Some(x) = args.byte_range { builder.add_byte_range(x); }
    builder.add_location_index(args.location_index);
    builder.finish()
  }


  #[inline]
  pub fn location_index(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(LocationRef::VT_LOCATION_INDEX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn byte_range(&self) -> Option<&'a ByteRange> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ByteRange>(LocationRef::VT_BYTE_RANGE, None)}
  }
}

impl flatbuffers::Verifiable for LocationRef<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u16>("location_index", Self::VT_LOCATION_INDEX, false)?
     .visit_field::<ByteRange>("byte_range", Self::VT_BYTE_RANGE, false)?
     .finish();
    Ok(())
  }
}
pub struct LocationRefArgs<'a> {
    pub location_index: u16,
    pub byte_range: Option<&'a ByteRange>,
}
impl<'a> Default for LocationRefArgs<'a> {
  #[inline]
  fn default() -> Self {
    LocationRefArgs {
      location_index: 0,
      byte_range: None,
    }
  }
}

pub struct LocationRefBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LocationRefBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_location_index(&mut self, location_index: u16) {
    self.fbb_.push_slot::<u16>(LocationRef::VT_LOCATION_INDEX, location_index, 0);
  }
  #[inline]
  pub fn add_byte_range(&mut self, byte_range: &ByteRange) {
    self.fbb_.push_slot_always::<&ByteRange>(LocationRef::VT_BYTE_RANGE, byte_range);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> LocationRefBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LocationRefBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<LocationRef<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for LocationRef<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("LocationRef");
      ds.field("location_index", &self.location_index());
      ds.field("byte_range", &self.byte_range());
      ds.finish()
  }
}
pub enum FileAttrsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FileAttrs<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for FileAttrs<'a> {
  type Inner = FileAttrs<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FileAttrs<'a> {
  pub const VT_INO: flatbuffers::VOffsetT = 4;
  pub const VT_SIZE: flatbuffers::VOffsetT = 6;
  pub const VT_MTIME: flatbuffers::VOffsetT = 8;
  pub const VT_CTIME: flatbuffers::VOffsetT = 10;
  pub const VT_KIND: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    FileAttrs { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FileAttrsArgs<'args>
  ) -> flatbuffers::WIPOffset<FileAttrs<'bldr>> {
    let mut builder = FileAttrsBuilder::new(_fbb);
    builder.add_size(args.size);
    builder.add_ino(args.ino);
    if let Some(x) = args.ctime { builder.add_ctime(x); }
    if let Some(x) = args.mtime { builder.add_mtime(x); }
    builder.add_kind(args.kind);
    builder.finish()
  }


  #[inline]
  pub fn ino(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(FileAttrs::VT_INO, Some(0)).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &FileAttrs) -> bool {
    self.ino() < o.ino()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: u64) -> ::core::cmp::Ordering {
    let key = self.ino();
    key.cmp(&val)
  }
  #[inline]
  pub fn size(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(FileAttrs::VT_SIZE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn mtime(&self) -> &'a Timespec {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Timespec>(FileAttrs::VT_MTIME, None).unwrap()}
  }
  #[inline]
  pub fn ctime(&self) -> &'a Timespec {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Timespec>(FileAttrs::VT_CTIME, None).unwrap()}
  }
  #[inline]
  pub fn kind(&self) -> FileType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<FileType>(FileAttrs::VT_KIND, Some(FileType::Regular)).unwrap()}
  }
}

impl flatbuffers::Verifiable for FileAttrs<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("ino", Self::VT_INO, false)?
     .visit_field::<u64>("size", Self::VT_SIZE, false)?
     .visit_field::<Timespec>("mtime", Self::VT_MTIME, true)?
     .visit_field::<Timespec>("ctime", Self::VT_CTIME, true)?
     .visit_field::<FileType>("kind", Self::VT_KIND, false)?
     .finish();
    Ok(())
  }
}
pub struct FileAttrsArgs<'a> {
    pub ino: u64,
    pub size: u64,
    pub mtime: Option<&'a Timespec>,
    pub ctime: Option<&'a Timespec>,
    pub kind: FileType,
}
impl<'a> Default for FileAttrsArgs<'a> {
  #[inline]
  fn default() -> Self {
    FileAttrsArgs {
      ino: 0,
      size: 0,
      mtime: None, // required field
      ctime: None, // required field
      kind: FileType::Regular,
    }
  }
}

pub struct FileAttrsBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> FileAttrsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ino(&mut self, ino: u64) {
    self.fbb_.push_slot::<u64>(FileAttrs::VT_INO, ino, 0);
  }
  #[inline]
  pub fn add_size(&mut self, size: u64) {
    self.fbb_.push_slot::<u64>(FileAttrs::VT_SIZE, size, 0);
  }
  #[inline]
  pub fn add_mtime(&mut self, mtime: &Timespec) {
    self.fbb_.push_slot_always::<&Timespec>(FileAttrs::VT_MTIME, mtime);
  }
  #[inline]
  pub fn add_ctime(&mut self, ctime: &Timespec) {
    self.fbb_.push_slot_always::<&Timespec>(FileAttrs::VT_CTIME, ctime);
  }
  #[inline]
  pub fn add_kind(&mut self, kind: FileType) {
    self.fbb_.push_slot::<FileType>(FileAttrs::VT_KIND, kind, FileType::Regular);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> FileAttrsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FileAttrsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<FileAttrs<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, FileAttrs::VT_MTIME,"mtime");
    self.fbb_.required(o, FileAttrs::VT_CTIME,"ctime");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for FileAttrs<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("FileAttrs");
      ds.field("ino", &self.ino());
      ds.field("size", &self.size());
      ds.field("mtime", &self.mtime());
      ds.field("ctime", &self.ctime());
      ds.field("kind", &self.kind());
      ds.finish()
  }
}
pub enum EntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Entry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Entry<'a> {
  type Inner = Entry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Entry<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_PARENT_INO: flatbuffers::VOffsetT = 6;
  pub const VT_ATTRS: flatbuffers::VOffsetT = 8;
  pub const VT_LOCATION_REF: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Entry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EntryArgs<'args>
  ) -> flatbuffers::WIPOffset<Entry<'bldr>> {
    let mut builder = EntryBuilder::new(_fbb);
    builder.add_parent_ino(args.parent_ino);
    if let Some(x) = args.location_ref { builder.add_location_ref(x); }
    if let Some(x) = args.attrs { builder.add_attrs(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Entry::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn parent_ino(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Entry::VT_PARENT_INO, Some(0)).unwrap()}
  }
  #[inline]
  pub fn attrs(&self) -> FileAttrs<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<FileAttrs>>(Entry::VT_ATTRS, None).unwrap()}
  }
  #[inline]
  pub fn location_ref(&self) -> Option<LocationRef<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<LocationRef>>(Entry::VT_LOCATION_REF, None)}
  }
}

impl flatbuffers::Verifiable for Entry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<u64>("parent_ino", Self::VT_PARENT_INO, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<FileAttrs>>("attrs", Self::VT_ATTRS, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<LocationRef>>("location_ref", Self::VT_LOCATION_REF, false)?
     .finish();
    Ok(())
  }
}
pub struct EntryArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub parent_ino: u64,
    pub attrs: Option<flatbuffers::WIPOffset<FileAttrs<'a>>>,
    pub location_ref: Option<flatbuffers::WIPOffset<LocationRef<'a>>>,
}
impl<'a> Default for EntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    EntryArgs {
      name: None, // required field
      parent_ino: 0,
      attrs: None, // required field
      location_ref: None,
    }
  }
}

pub struct EntryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Entry::VT_NAME, name);
  }
  #[inline]
  pub fn add_parent_ino(&mut self, parent_ino: u64) {
    self.fbb_.push_slot::<u64>(Entry::VT_PARENT_INO, parent_ino, 0);
  }
  #[inline]
  pub fn add_attrs(&mut self, attrs: flatbuffers::WIPOffset<FileAttrs<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<FileAttrs>>(Entry::VT_ATTRS, attrs);
  }
  #[inline]
  pub fn add_location_ref(&mut self, location_ref: flatbuffers::WIPOffset<LocationRef<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<LocationRef>>(Entry::VT_LOCATION_REF, location_ref);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Entry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Entry::VT_NAME,"name");
    self.fbb_.required(o, Entry::VT_ATTRS,"attrs");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Entry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Entry");
      ds.field("name", &self.name());
      ds.field("parent_ino", &self.parent_ino());
      ds.field("attrs", &self.attrs());
      ds.field("location_ref", &self.location_ref());
      ds.finish()
  }
}
pub enum VolumeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Volume<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Volume<'a> {
  type Inner = Volume<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Volume<'a> {
  pub const VT_VERSION: flatbuffers::VOffsetT = 4;
  pub const VT_LOCATIONS: flatbuffers::VOffsetT = 6;
  pub const VT_ENTRIES: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Volume { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args VolumeArgs<'args>
  ) -> flatbuffers::WIPOffset<Volume<'bldr>> {
    let mut builder = VolumeBuilder::new(_fbb);
    builder.add_version(args.version);
    if let Some(x) = args.entries { builder.add_entries(x); }
    if let Some(x) = args.locations { builder.add_locations(x); }
    builder.finish()
  }


  #[inline]
  pub fn version(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Volume::VT_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn locations(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<LocationWrapper<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<LocationWrapper>>>>(Volume::VT_LOCATIONS, None).unwrap()}
  }
  #[inline]
  pub fn entries(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Entry<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Entry>>>>(Volume::VT_ENTRIES, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for Volume<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("version", Self::VT_VERSION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<LocationWrapper>>>>("locations", Self::VT_LOCATIONS, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Entry>>>>("entries", Self::VT_ENTRIES, true)?
     .finish();
    Ok(())
  }
}
pub struct VolumeArgs<'a> {
    pub version: u64,
    pub locations: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<LocationWrapper<'a>>>>>,
    pub entries: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Entry<'a>>>>>,
}
impl<'a> Default for VolumeArgs<'a> {
  #[inline]
  fn default() -> Self {
    VolumeArgs {
      version: 0,
      locations: None, // required field
      entries: None, // required field
    }
  }
}

pub struct VolumeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> VolumeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u64) {
    self.fbb_.push_slot::<u64>(Volume::VT_VERSION, version, 0);
  }
  #[inline]
  pub fn add_locations(&mut self, locations: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<LocationWrapper<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Volume::VT_LOCATIONS, locations);
  }
  #[inline]
  pub fn add_entries(&mut self, entries: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Entry<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Volume::VT_ENTRIES, entries);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> VolumeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    VolumeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Volume<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Volume::VT_LOCATIONS,"locations");
    self.fbb_.required(o, Volume::VT_ENTRIES,"entries");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Volume<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Volume");
      ds.field("version", &self.version());
      ds.field("locations", &self.locations());
      ds.field("entries", &self.entries());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Volume`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_volume_unchecked`.
pub fn root_as_volume(buf: &[u8]) -> Result<Volume, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Volume>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Volume` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_volume_unchecked`.
pub fn size_prefixed_root_as_volume(buf: &[u8]) -> Result<Volume, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Volume>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Volume` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_volume_unchecked`.
pub fn root_as_volume_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Volume<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Volume<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Volume` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_volume_unchecked`.
pub fn size_prefixed_root_as_volume_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Volume<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Volume<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Volume and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Volume`.
pub unsafe fn root_as_volume_unchecked(buf: &[u8]) -> Volume {
  unsafe { flatbuffers::root_unchecked::<Volume>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Volume and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Volume`.
pub unsafe fn size_prefixed_root_as_volume_unchecked(buf: &[u8]) -> Volume {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Volume>(buf) }
}
#[inline]
pub fn finish_volume_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Volume<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_volume_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Volume<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
