[package]
name = "cfs-fuse"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
cfs-core.workspace = true

bytesize.workspace = true
clap = { workspace = true, features = ["derive"] }
fuser = { workspace = true, default_features = false, features = [] }
libc.workspace = true
object_store = { workspace = true, features = ["aws"] }
reqwest.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
