[package]
name = "cfs-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bytes.workspace = true
flatbuffers.workspace = true
futures.workspace = true
uuid.workspace = true
