[package]
name = "cfs-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bytes.workspace = true
dashmap.workspace = true
flatbuffers.workspace = true
futures.workspace = true
object_store.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
rand = "0.9.2"
