[package]
name = "cfs-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
dashmap.workspace = true
flatbuffers.workspace = true
futures.workspace = true
object_store.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
paste = "1.0.15"
rand = "0.9.2"
tempfile.workspace = true
